Traceback (most recent call last):
  File "music_chart.py", line 19, in <module>
    APP_NAME = os.environ["LAST_FM_APP_NAME"]
  File "/Users/dchege711/anaconda3/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'LAST_FM_APP_NAME'
To https://github.com/dchege711/dchege711.github.io.git
   610a897..e12391b  master -> master
Traceback (most recent call last):
  File "music_chart.py", line 19, in <module>
    APP_NAME = os.environ["LAST_FM_APP_NAME"]
  File "/Users/dchege711/anaconda3/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'LAST_FM_APP_NAME'
To https://github.com/dchege711/dchege711.github.io.git
   e12391b..85b09d5  master -> master
Traceback (most recent call last):
  File "music_chart.py", line 19, in <module>
    APP_NAME = os.environ["LAST_FM_APP_NAME"]
  File "/Users/dchege711/anaconda3/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'LAST_FM_APP_NAME'
